import { StyleSheet } from 'react-native';

const DetailsArmoireStyle = StyleSheet.create({
  
    scrollContainer: {
        flexGrow: 1,
        paddingBottom: 20,
      },
      container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f7f8fa',
      },
      largePhoto: {
        width: '100%',
        height: 450,
        borderRadius: 15,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 8,
      },
      title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 15,
        textAlign: 'center',
        color: '#1b484e',
      },
      infoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 10,
        paddingHorizontal: 10,
        paddingVertical: 8,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
      },
      textContainer: {
        flex: 1,
        marginLeft: 10,
      },
      Prebold: {
        fontSize: 16,
        fontWeight: 'bold',
        marginRight: 5,
      },
      metadata: {
        flex: 1,
        flexWrap: 'wrap',
        flexShrink: 1,
        fontSize: 15,
      },
      button: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#1abc9c',
        padding: 15,
        marginVertical: 10,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 6,
      },
      iconStyle: {
        marginRight: 10,
      },
      buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
      },
      footer: {
        backgroundColor: '#f7f8fa',
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
      },
      saveButton: {
        backgroundColor: '#e63946',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        width: '100%',
      },
      additionalPhoto: {
        width: 350,
        height: 150,
        marginBottom: 30,
        borderRadius: 10,
      },
      
      // DetailsArmoireStyle pour la liste des installations
      listContainer: {
        paddingVertical: 10,
      },
      card: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderRadius: 12,
        marginVertical: 8,
        marginHorizontal: 10,
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowRadius: 10,    
        elevation: 5,        
        overflow: 'hidden',
      },
      groupContainer: {
        marginBottom: 2,
      },
      groupTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginVertical: 10,
      },
      cardImage: {
        width: 100,
        height: 100,
      },
      cardContent: {
        flex: 1,
        padding: 10,
        justifyContent: 'center',
      },
      cardTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#2c3e50',
        bottom:20,
      },
      cardText:{
        color: '#3498db',
        bottom:10,
      },
      noDataText: {
        textAlign: 'center',
        color: '#7f8c8d',
        fontSize: 16,
        marginTop: 0,
        marginBottom: 15,
      },
      fullscreenModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.9)', 
      },
      fullscreenImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain', 
      },
      fullscreenModalClose: {
        position: 'absolute',
        top: 40,
        right: 20,
        zIndex: 1,
      },
      fullscreenModalContent: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      fullscreenCommentContainer: {
        position: 'absolute',
        bottom: 100,
        left: 20,
        right: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        borderRadius: 20,
        padding: 10,
      },
      fullscreenComment: {
        fontSize: 16,
        color: '#fff',
        textAlign: 'center',
      },
      modalTopButtons: {
        position: 'absolute',
        top: 40,
        left: 20,
        right: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        zIndex: 2,
      },
      iconButton: {
        backgroundColor: 'rgba(27, 72, 78, 0.7)',
        padding: 10,
        borderRadius: 30,
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
      },
      transparentCommentContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 15,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.0)',
      },
      transparentCommentInput: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        borderRadius: 40,
        paddingHorizontal: 20,
        paddingVertical: 12,
        fontSize: 16,
        marginRight: 0,
        color: '#fff',
      },
      saveIconInsideInput: {
        height:42,
        width:42,
        backgroundColor: '#1b484e',
        margin: 5,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.75)',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        overflow: 'hidden',
      },
      modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalContent: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 20,
        width: '80%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 5,
      },
      modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 20,
        color: '#1b484e',
      },
      modalOption: {
        padding: 15,
        width: '100%',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
      },
      modalText: {
        fontSize: 16,
        color: '#34495e',
      },
      optionActive: {
        backgroundColor: '#e0f7fa',
        borderRadius: 10,
      },
      modalCloseButton: {
        marginTop: 20,
        padding: 12,
        backgroundColor: '#e0e0e0',
        borderRadius: 8,
        width: '100%',
        alignItems: 'center',
      },
      modalCloseText: {
        fontSize: 16,
        color: '#333',
      },
      commentContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        padding: 15,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
      },
      commentSection: {
        flex: 1,
        marginLeft: 10,
      },
      commentText: {
        fontSize: 16,
        color: '#34495e',
      },
      commentInputContainer: {
        borderWidth: 1,
        borderColor: '#1abc9c',
        borderRadius: 40,
        padding: 2,
      },
      commentInput: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        borderRadius: 40,
        paddingHorizontal: 20,
        paddingVertical: 12,
        fontSize: 16,
        color: '#34495e',
      },
      commentInputActive: {},
      errorText: {
        color: 'red',
        textAlign: 'center',
        marginTop: 10,
      },
    });
    
    

export default DetailsArmoireStyle;
