import { StyleSheet } from 'react-native';

const FormStyle = StyleSheet.create({

    formContainer: {
        padding: 20,
        backgroundColor: '#f7f7f7',
        borderRadius: 20,
        width: '95%',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 10,
      },
      title: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#1b484e',
        textAlign: 'center',
        marginBottom: 20,
      },
      input: {
        height: 50,
        borderColor: '#ccc',
        borderWidth: 1,
        marginBottom: 15,
        paddingHorizontal: 15,
        borderRadius: 10,
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
      },
      pickerButton: {
        borderWidth: 1,
        borderColor: '#ccc',
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        backgroundColor: '#f9f9f9',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
      },
      pickerTitle: {
        marginBottom: 5,
        fontWeight: 'bold',
        fontSize: 16,
        color: '#333',
      },
      button: {
        backgroundColor: '#1b484e',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 10,
      },
      buttonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
      },
      saveButton: {
        backgroundColor: '#4caf50',
      },
      modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
      },
      modalContent: {
        backgroundColor: '#fff',
        padding: 25,
        borderRadius: 15,
        width: '85%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 15,
      },
      modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 20,
      },
      modalButton: {
        backgroundColor: '#4caf50',
        padding: 15,
        borderRadius: 10,
        marginTop: 15,
        alignItems: 'center',
        width: '100%',
      },
    });

export default FormStyle;